version: '3'
services:
  traefik:
    image: arm64v8/traefik:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik

  node-app:
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 15s

    build:
      context: .
      args:
        - NODE_ENV=production

    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}

    command: node index.js
    labels:
      - "traefik.http.routers.node-app.rule=(`${DOMAIN}`)"
      - "traefik.http.routers.node-app.entrypoints=web"

  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
