version: '3'
services:
  node-app:
    build: .
    image: mnshkv/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo-db
      - redis

  mongo-db:
    image: arm64v8/mongo:4.2-bionic
    volumes:
      - mongo-gigboy:/data/db:rw
  redis:
    image: arm64v8/redis

volumes:
  mongo-gigboy: null
