version: '3'
services:
  traefik:
    image: arm64v8/traefik:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REGRU_USERNAME=${REGRU_USERNAME}
      - REGRU_PASSWORD=${REGRU_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik

  node-app:
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 15s

    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}

    command: node index.js
    labels:
      - "traefik.http.routers.node-app.rule=(`${DOMAIN}`)"
      - "traefik.http.routers.node-app.entrypoints=web"
      - "traefik.http.routers.node-app.entrypoints=websecure"
      - "traefik.http.routers.node-app.tls.certresolver=myresolver"

  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
