version: '3'
services:
  nginx:
    image: arm64v8/nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - node-app

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=gigboy
      - MONGO_PASSWORD=PASSWORD
      - SESSION_SECRET=secret
    command: npm run dev
  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gigboy
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
