providers:
  docker: true
  # Говорит traefik'у, что мы работаем с docker

entrypoints:
  web:
  # Название точки входа, к которой будут подключатся другие контейнеры.
  # может быть любым. Главное, чтобы совпадал с названием в других местах.
    address: :80
    # traefik будет доступен на 80 порту.
  websecure:
    address: :443

certificatesresolvers:
  myresolver:
  # Название может быть любым. К этому блоку будут обращатся контейнеры для получения сертификатов
    acme:
    # Здесь будут находится настройки для получения сертификатов.
      storage: /etc/traefik/acme.json
      # Включаем сохранение информации о полученых сертификатах в папку "traefik",
      # чтобы не генерировать их каждый раз при запуске контейнера.
      # Если сертификат ранее был создан и является актуальным,
      # то traefik возьмет его из файла "acme.json"